version: "3"

services:
  bot:
    build: .
    env_file:
      - .env

  redis:
    image: redis:7.0.7-alpine

  mongodb:
    image: mongo:4.4.13
    volumes:
      - mongodb:/data/db
    env_file:
      - .env.mongodb

volumes:
  mongodb: