version: "3"

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:7.0.7-alpine
    restart: unless-stopped

  mongodb:
    image: mongo:6.0.3
    restart: unless-stopped
    env_file:
      - .env.mongodb
